[workspace]
resolver = "2"
members = [ "components", "config", "generate_pages","pages"]

[workspace.dependencies]
coyote = { git = "https://github.com/wolfpup-software/coyote-rs", version = "0.1" }
coyote_html = { git = "https://github.com/wolfpup-software/coyote-rs", version = "0.1" }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snowprints = { git = https://github.com/taylor-vann/snowprints, version = "0.1" }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
walk_directory = { git = "https://github.com/wolfpup-software/walk_directory-rs", version = "0.1" }
